### ISSUE TITLE
asdf.open leaves behind an open file if it can't sort out how to open it

### ISSUE THREAD

**Issue by jdavies-st** [asdf-format/asdf#1006]
The following test illustrates:

```python
# test_open_fail.py

from pathlib import Path

import asdf
import pytest


def test_asdf(tmp_path):
    path = tmp_path / "empty.asdf"
    Path(path).touch()

    with asdf.open(path) as af:
        pass
```

When run with `pytest test_open_fail.py --open-files`, the test fails as expected with

```
E           ValueError: Input object does not appear to be an ASDF file or a FITS with ASDF extension
```

But also produces a teardown error, since it leaves the file open:

```
E           AssertionError: File(s) not closed:
E             /private/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/pytest-of-jdavies/pytest-157/test_asdf0/empty.asdf
```

**Comment by WilliamJamieson** [comment]
I believer the issue is that it throws an error during the open process. The real issue here is that asdf apparently does not support opening empty files.

**Comment by WilliamJamieson** [comment]
@perrygreenfield what do you think?

**Comment by jdavies-st** [comment]
The issue is that when it fails to open a file, it leaves behind an open file handle instead of cleaning it up upon raising the exception.  I.e. the open function doesn't act like a proper context manager here.

**Comment by WilliamJamieson** [comment]
Well looking at the code, `asdf.open` isn't a "real context manager", so its not surprising that we get this sort of issue. I will look into what needs to be done to actually make it work as one.

**Comment by WilliamJamieson** [comment]
Indeed, the source of the non-context manager like behavior is here: https://github.com/asdf-format/asdf/blob/03e7a4ad9186daf2f01d5a3df9e1431da17134e0/asdf/generic_io.py#L1022

If one artificially breaks the code right before this `open` call we do not leave an open file dangling, but if we break right after (as this test does due to the fact that it is an empty file), we do get a dangling file. Which makes perfect sense because `fd.close` can never be called prior to exiting in this case.

@eslavich do you have any ideas on how to make `asdf.open` a proper context manager?

**Comment by jdavies-st** [comment]
The intent has always been to have `asdf.open` work like a context manager.  I.e.:

https://github.com/asdf-format/asdf/blob/03e7a4ad9186daf2f01d5a3df9e1431da17134e0/asdf/asdf.py#L278-L282

But it didn't.  @drdavella did a lot of refactoring to get it to mostly behave like a context manager, even when files were memory mapped.

And this issue points out a final (hopefully?) remaining bug.

Btw, not mentioned in the issue is that the `pytest-openfiles` plugin is used to check in the above test.

**Comment by eslavich** [comment]
I haven't investigated this, but I doubt it's an issue with the `AsdfFile` context manager being implemented incorrectly.  If we're throwing an exemption out of `asdf.open` then Python does not have a chance to call either `__enter__` or `__exit__` on the `AsdfFile` object.  What we probably need to do is wrap the innards of `asdf.open` in a try/except and keep track of the files we open so that if there is a problem we can close them before allowing the exception to bubble up.

**Comment by WilliamJamieson** [comment]
This is the only thing I could come up with.
