### ISSUE TITLE
asdf disables colorama in Jupyter

### ISSUE THREAD

**Issue by ItayKishon-Vayyar** [asdf-format/asdf#1017]
It seems when importing asdf, the [colorama](https://pypi.org/project/colorama/) functionallity is disabled.

See the following, to be run in two distinct cells (if all in the same cell, it would run correctly on the first time, yet not on the following times):
```
from colorama import Fore
print(Fore.RED + "I'm red.")
``` 

```
import asdf
print(Fore.RED + "I'm not...")
```

![image](https://user-images.githubusercontent.com/68048422/130580987-43bdc938-5475-4927-b36e-c19d2772c71a.png)

versions: Python 3.8.3, Jupyter Lab 2.1.5, asdf 2.7.1

Thanks.

**Comment by eslavich** [comment]
The problem seems to be that we're calling `colorama.init` as part of the import:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/2895013/130624119-e7b09ea2-dde5-409a-8f9c-40dfb1c9e360.png">

I'm not sure why that affects the output in a notebook -- the colorama docs claim that the init function "has no effect" on non-Windows platforms.

In any case, we probably shouldn't be calling init at import time.  We can move that call inside the class that actually uses colorama which should solve the problem most of the time.

**Comment by ItayKishon-Vayyar** [comment]
It seems to be a problem specific to Windows (which is what I'm using, BTW) - as you can see in both examples, colorama functions correctly prior to calling `init()`.
If you were to keep using `init()`, regardless of when, it would still cause colorama to stop functioning.

Perhaps the solution should be to check the OS, and call `init()` only on non-windows systems? Or perhaps on non-Jupyter interfaces?

**Comment by eslavich** [comment]
There's some discussion on the colorama repo that suggests that notebooks are not supported:

https://github.com/tartley/colorama/issues/63

My example is on macOS, by the way...
