### ISSUE TITLE
Cyclic build dependency asdf-transform-schemas and asdf-standard

### ISSUE THREAD

**Issue by olebole** [asdf-format/asdf#1093]
While trying to package asdf 2.10 for Debian, I found that it has a new dependency on [asdf-transform-schemas](https://github.com/asdf-format/asdf-transform-schemas) and [asdf-standard](https://github.com/asdf-format/asdf-standard) https://github.com/asdf-format/asdf/blob/3483bfe273205eac39ca20097b2af7a27a3283be/setup.cfg#L28-L37
asdf-transform-schemas however already [depends on asdf](https://github.com/asdf-format/asdf-transform-schemas/blob/f2eeb2dc767c0a3df964a99397baf57060a3f629/setup.cfg#L18-L20), the same for [asdf-standards](https://github.com/asdf-format/asdf-standard/blob/c7360d1a5ef66af68f13f84a2b16c1de0b6c55b9/setup.cfg#L22-L24).

This is unfortunate, since is doesn't allow bootstrapping from sources only, and therefore complicates builds. Would it be possible to break these dependency loops up?

**Comment by WilliamJamieson** [comment]
@olebole, we should be able to solve this issue with some exchange of code between asdf and asdf-standard.

Essentially, asdf-standard and asdf-transform-schemas only need asdf as a dependency so that they can use the `DirectoryResourceMapping` object in order to register their schemas in the asdf entry points. Since asdf-standard will always be a dependency of asdf, we will move `DirectoryResourceMapping` to asdf-standard (dropping the asdf requirement in the process) and make it a requirement of both asdf-transform-schemas and asdf.

All of these changes will require releasing new versions of asdf-standard, asdf-transform-schemas, and asdf in order for the fix to work.

**Comment by marscher** [comment]
I guess I would also be able to install asdf-standard and asdf-transform-schemas from conda-forge once this has been done, right?

**Comment by WilliamJamieson** [comment]
> I guess I would also be able to install asdf-standard and asdf-transform-schemas from conda-forge once this has been done, right?

I believe so.

**Comment by olebole** [comment]
Thank you! For me, new versions are not a problem. I anyway need to [package the Python package for the standard](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006200) first.

**Comment by WilliamJamieson** [comment]
The release has not occurred yet. It should be occurring shortly.

**Comment by WilliamJamieson** [comment]
@olebole the [asdf 2.10.1 release](https://github.com/asdf-format/asdf/releases/tag/2.10.1) is now out. Please let me know if you have any more issues with packaging asdf.

**Comment by olebole** [comment]
Thank you! I will update everything shortly. And I will report new issues when they appear :grin:
