### ISSUE TITLE
Flakey test

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf#1298]
The test: https://github.com/asdf-format/asdf/blob/a2d2c4723ab8a8cdc0eb3f87fb913a80d728e5b9/asdf/tests/test_array_blocks.py#L834-L851

introduced in #1280 seems to be intermittently flaky for reasons I cannot explain. I see failures in the CI

See:

- https://github.com/asdf-format/asdf/actions/runs/3903417026/jobs/6667758950
- https://github.com/asdf-format/asdf/actions/runs/3880159122/jobs/6618149855

But when simply re-running the CI:

- https://github.com/asdf-format/asdf/actions/runs/3903417026/jobs/6668675088
- https://github.com/asdf-format/asdf/actions/runs/3885577317/jobs/6629628167 (note that I did some debugging before making an identical re-run)

The CI passes. I don't think this is related to the changes PR #1293, though all the failures are in CI for those changes. I think the issue is more that #1293 happens to have run the CI many times.

**Comment by WilliamJamieson** [comment]
@eslavich do you have any thoughts?

**Comment by braingram** [comment]
I pulled code out of the test and modified it to repeatedly run.
```python
import numpy as np


file_path = "test.asdf"

array = np.arange(200)
af = asdf.AsdfFile({"array": array})
af.write_to(file_path)

with asdf.open(file_path, lazy_load=True, copy_arrays=True) as af:
    i = 0
    while True:
        original_id = id(af.blocks.get_block(0).data)
        assert id(af.blocks.get_block(0).data) == original_id
        i += 1
        print(i)
```
This fails on my machine after ~500 iterations.
```
508
509
510
Traceback (most recent call last):
  File "/Users/bgraham/projects/221220_eslavich_weakref_cache/tests/torture.py", line 16, in <module>
    assert id(af.blocks.get_block(0).data) == original_id
AssertionError
```

If I add `af['array'][0]` right before `i = 0` the test re-runs without issue.

I can see 2 options for addressing this:
- update the test to explicitly access the array (add `af['array'][0]`) which will cause NDArrayType to load and keep a refence to data.
- revert PR #1280 

I'm inclined to revert the PR because this feature (removing the block cache) is only useful for non-NDArrayType objects that use block storage. These types of objects are not yet supported so it seems unnecessarily risky to include the weakref block cache in the next release. I propose that we revert the PR and include the feature when we're ready to support non-NDArrayType objects that use block storage. I will open a draft PR with the reversion in case we choose that option.
