### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf#1478]
Now that ASDF 3.0 is about to be release, we should update ASDF (and related packages) to use `main` as the primary branch instead of `master`.

**Comment by braingram** [comment]
Sounds good to me.

Do you have a proposal for how to make these changes?

Some specific questions I have are:
- Do you have a preference for ordering a fix for this issue with https://github.com/asdf-format/asdf/issues/1373?
- Are you aware of any non-asdf packages that test against our git repo other than astropy?

**Comment by braingram** [comment]
> I don't have a preference. Though I don't see that this has much to do with #1373.

There are many references to branch names in the release process wiki page. I think it makes sense to rename the branch first but wanted to bring it up in case you were already working on an update to the page.

> There are several, but thats a relatively simple fix those packages can make. Many of those projects will need to switch to using the 2.15.x branch for testing anyways.

Which packages are these?

> The STScI guidance for inclusive technical language indicates that we should be making this change. Personally, it has bothered me that ASDF has not made this change, but when I started working on ASDF the decision was made that we would make the `master` to `main` name change once we fully switched over to 3.0 development. I see that point as when 2.15.0 is released. The rest of the `asdf-format` repositories should follow suite with ASDF.

Am I reading this right that you want to rename the branch when 2.15 is released? Any reasons to not do it now?

**Comment by WilliamJamieson** [comment]
> Am I reading this right that you want to rename the branch when 2.15 is released? Any reasons to not do it now?

Not really, in the original discussion thats what was decided. I am fine with making this change sooner rather than later.

**Comment by braingram** [comment]
There are several PRs now open to allow CI jobs to use the default branches (rather than hard coding `master` or `main`). These should probably be merged first as they should allow for later renaming default branches without breaking ci. These PRs are:
-	https://github.com/asdf-format/asdf-fits-schemas/pull/15
-	https://github.com/asdf-format/asdf-table-schemas/pull/14
-	https://github.com/asdf-format/asdf-time-schemas/pull/14
-	https://github.com/asdf-format/asdf-unit-schemas/pull/20
-	https://github.com/asdf-format/asdf-transform-schemas/pull/85
-	https://github.com/asdf-format/asdf-standard/pull/370

(note that several of the above have CI failures due to unrelated outdated CI, including outdated pre-commit and weldx CI failure possibly due to https://github.com/asdf-format/asdf/pull/1340).

There are a few repositories that require renaming of the default branch (quite a few already have `main`). There are PRs open for:
-	https://github.com/asdf-format/asdf-transform-schemas/pull/86
-	https://github.com/asdf-format/sphinx-asdf/pull/55
-	https://github.com/asdf-format/asdf-standard/pull/371
-	https://github.com/asdf-format/asdf/pull/1479

Each should be closely followed by a branch rename and the last two (asdf-standard and asdf) should likely be done together (as mentioned: https://github.com/asdf-format/asdf/pull/1479#discussion_r1134502882).

There are two repositories without dependents (or ci) that can possibly just be renamed:
- https://github.com/asdf-format/tutorials
- https://github.com/asdf-format/asdf-cpp

**Comment by braingram** [comment]
Fixed in: https://github.com/asdf-format/asdf/pull/1479
