### ISSUE TITLE
Support MaskedQuantity

### ISSUE THREAD

**Issue by nstarman** [asdf-format/asdf#1640]
Astropy (v5.0+) has the `Masked` class (https://docs.astropy.org/en/stable/utils/masked/index.html), which can produce `MaskedQuantity`. It would be great if ASDF could serialize Masked objects.

**Comment by braingram** [comment]
Thanks for opening this issue. That's a great thing to consider.

astropy objects are currently supported by asdf-astropy which is likely where `MaskedQuantity` support would fit in. I'm unable to transfer this issue to that repository (it's in a different organization) so please feel free to open this issue with asdf-astropy: https://github.com/astropy/asdf-astropy/issues

Since I'm unable to transfer this, I'm going to close this issue with this comment but please open the issue with asdf-astropy.
