### ISSUE TITLE
Reaching out / sending scientific data to JavaScript

### ISSUE THREAD

**Issue by almarklein** [asdf-format/asdf#377]
Hi,

This comment is a combination of thanks, feedback, and shameless advertisement for a competitive format.

First off, Thanks for all the work on ASDF! Over the years I've myself struggled with serializing scientific data, and ASDF seems like it would have solved many of my problems :)

I've been annoyed with the limitations of JSON and HDF5 for some time now, and more recently I also got a need to send scientific data between Python and JavaScript. I was happy to see how well ASDF aligned with my needs, and I find the combination of a readable format and binary data very appealing.

Although ASDF ticked most of the boxes, it missed a few critical ones; I want to send (scientific) data between Python and JavaScript (over a WebSocket) and for this ASDF seems unsuited. Perhaps this is simply not within the scope of ASDF, but I'd like to share it as feedback:
* I'd have to implement ASDF in JS, which seems quite a bit of work. Parsing YAML in JS seems not trivial. It seems that the nice feature of human readability plus binary data is paid for by a more complex format.
* Parsing YAML is generally slow (performance is quite bad compared to e.g. JSON), which can probably be explained by the fact that the format is much less "strict" than e.g. JSON, but also because JSON is more prevalent and therefore its libs better optimized. I see how this is not much of a problem when most of the data consists of arrays, but in my case I might have many small messages, or messages consisting mostly of lists and dicts, and performance is important in my use-case.

In the end, I started working on a new format, taking inspiration from ASDF. The main difference is that it's a full binary format. It was a bit painful to let go of human readability, but it allows the format to be simple and fast to parse. It's called BSDF, and the code and docs are here: https://gitlab.com/almarklein/bsdf

Sorry for the shameless advertisement, but I reckoned that there might be people here who might be interested. The project is nearing a state suited for release and I am eager to get feedback while I can still make changes without caring about backward compatibility.

I am aware that although BSDF ticks my boxes, other people have other requirements. In aiming for simplicity, BSDF no doubt lacks features that ASDF does have. I am interested to learn more about where the formats are different so that this can be documented better.

**Comment by drdavella** [comment]
Hi @almarklein, thanks for getting in touch, and best of luck to you with BSDF.

Just out of curiosity, if ASDF used JSON instead of YAML for its metadata representation, would that have met your needs? We have had some internal discussion recently about whether strict JSON representation would be good to support. As you point out, this would make it much easier to implement ASDF in JavaScript. Also, there is clearly a larger community supporting JSON than there is supporting YAML. It should be straightforward to convert an existing ASDF file to one that uses JSON for its metadata representation.

**Comment by almarklein** [comment]
Using JSON instead of YAML would certainly help, though some issues would persist, e.g.:
* No way to encode `nan` and `inf` in the metadata.
* Still a little inefficient if data consists mainly of non-binary data, though most JSON implementations are pretty darn fast.

Despite these, yes, I might not have gone through the trouble of building BSDF if ASDF used JSON at the time. I assumed that JSON was not an option because ASDF made use of specifuc YAML features, like references. I guess I was wrong.

**Comment by drdavella** [comment]
You're not wrong: but I think the features of YAML that we're using (like references) could be pushed into the ASDF library itself in order to support JSON, if that makes sense. I think it's true that there are conventions for using references in JSON, even if it's not officially supported, but I need to do a bit more research.

**Comment by braingram** [comment]
Closing this with thoughts of what will be in `csdf` :)
